services:
  db:
    image: postgres:17.5
    container_name: conference-platform-db
    environment:
      POSTGRES_USER: conference_platform_db_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: conference_platform_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "11234:5432"

volumes:
  db_data:
